# AppVeyor CI build file, https://ci.appveyor.com/project/HangfireIO/hangfire-build

#---------------------------------#
#    environment configuration    #
#---------------------------------#

version: build.{build}

environment:
  SIGNPATH_API_TOKEN:
    secure: RjoKtWzTX30wRKFS8v4SWnBZq3sXeNwt0LsHTsrJYQfzKbBqGkeKsTpGnaqf1t4L

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - pwsh: Install-PSResource -Name SignPath -TrustRepository

# to run your custom scripts instead of automatic MSBuild
build_script: build.bat sign

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\**\*.nupkg'
  - path: 'build\**\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key: 
      secure: oJ1idcCpD1o6Q2cXBVlGBPYwbDvlOXDY1+Qln0wDdHkybxLHApLv/G+4hiWbtTBH
    on:
      appveyor_repo_tag: true
