# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/hangfire

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script: build.bat

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\**\*.nupkg'
  - path: 'build\**\*.zip'
